
package nmea.ui.viewer;

import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RadialGradientPaint;
import java.awt.RenderingHints;

import java.awt.Stroke;

import java.awt.font.TextAttribute;

import java.text.AttributedString;

import java.text.DecimalFormat;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import nmea.event.NMEAReaderListener;

import nmea.server.ctx.NMEAContext;

import nmea.server.ctx.NMEADataCache;

import nmea.server.utils.ChartColor;

import ocss.nmea.parser.SVData;

/**
 *
 * @author olediour
 */
public class GPSSatellitesPanel
  extends javax.swing.JPanel
{
  private final static DecimalFormat DF2 = new DecimalFormat("00");
  
  /** Creates new form GPSSatellitesPanel */
  public GPSSatellitesPanel()
  {
    initComponents();
    NMEAContext.getInstance().addNMEAReaderListener(new NMEAReaderListener()
    {
      public void manageNMEAString(String str)
      {
//      System.out.println("NMEA:" + str);
        if (str.trim().length() > 6 && str.startsWith("$"))
        {
          if (str.substring(3, 6).equals("GSV"))
          {
            try
            {
              if (NMEAContext.getInstance().getCache().get(NMEADataCache.SAT_IN_VIEW) != null)
              {
                Map<Integer, SVData> hm = ( Map<Integer, SVData>)NMEAContext.getInstance().getCache().get(NMEADataCache.SAT_IN_VIEW);
                
                System.out.println(hm.size() + " Satellites in view:");
                for (Integer sn : hm.keySet())
                {
                  SVData svd = hm.get(sn);
                  System.out.println("Satellite #" + svd.getSvID() + " Elev:" + svd.getElevation() + ", Z:" + svd.getAzimuth() + ", SNR:" + svd.getSnr() + "db. ");
                }
              }
            }
            catch (Exception ex)
            {
              // No cache yet
            }
          }
        }
      }
    });
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents()//GEN-BEGIN:initComponents
  {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
  public void paintComponent(Graphics gr)
  {    
    ((Graphics2D)gr).setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                                      RenderingHints.VALUE_TEXT_ANTIALIAS_ON);      
    ((Graphics2D)gr).setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                                      RenderingHints.VALUE_ANTIALIAS_ON);  
    int width  = this.getWidth();
    int height = this.getHeight();
    int radius = (int)(0.9 * Math.min(width, height) / 2);
    Point center = new Point(width / 2, height / 2);
//  gr.setColor(Color.black);
//  gr.fillOval(center.x - radius, center.y - radius, 2 * radius, 2 * radius);
    Graphics2D g2d = (Graphics2D)gr;
    if (true) // With shaded bevel
    {
      RadialGradientPaint rgp = new RadialGradientPaint(center, 
                                                        (int)(radius * 1.15), 
                                                        new float[] {0f, 0.9f, 1f}, 
                                                        new Color[] {this.getBackground(), Color.gray, this.getBackground()});
      g2d.setPaint(rgp);
      g2d.fillRect(0, 0, width, height);
    }
    drawGlossyCircularDisplay((Graphics2D)gr, center, radius, Color.lightGray, Color.black, 1f);
    // Grid
    gr.setColor(Color.gray);
    Stroke origin = g2d.getStroke();
    Stroke dotted = new BasicStroke(1, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0, new float[] { 5 }, 0);
    g2d.setStroke(dotted);
    g2d.drawLine(center.x, center.y - radius, center.x, center.y + radius); // N-S
    g2d.drawLine(center.x - radius, center.y, center.x + radius, center.y); // E-W
    g2d.drawLine(center.x - (int)((Math.cos(Math.PI / 4d) * radius)), // NW-SE
                 center.y - (int)((Math.sin(Math.PI / 4d) * radius)), 
                 center.x + (int)((Math.cos(Math.PI / 4d) * radius)), 
                 center.y + (int)((Math.sin(Math.PI / 4d) * radius))); 
    g2d.drawLine(center.x + (int)((Math.cos(Math.PI / 4d) * radius)), // NE-SW
                 center.y - (int)((Math.sin(Math.PI / 4d) * radius)), 
                 center.x - (int)((Math.cos(Math.PI / 4d) * radius)), 
                 center.y + (int)((Math.sin(Math.PI / 4d) * radius))); 
    g2d.drawOval(center.x - (int)(radius * (1d/3d)), 
                 center.y - (int)(radius * (1d/3d)), 
                 2 * (int)(radius * (1d/3d)), 
                 2 * (int)(radius * (1d/3d)));
    g2d.drawOval(center.x - (int)(radius * (2d/3d)), 
                 center.y - (int)(radius * (2d/3d)), 
                 2 * (int)(radius * (2d/3d)), 
                 2 * (int)(radius * (2d/3d)));    
    g2d.setStroke(origin);
    Font origFont = g2d.getFont();
    g2d.setFont(origFont.deriveFont(Font.BOLD, 40f));
    String north = "N";
    int strWidth  = g2d.getFontMetrics(g2d.getFont()).stringWidth(north);
    g2d.drawString(north, center.x - (strWidth / 2), center.y - radius + g2d.getFont().getSize());
    g2d.setFont(origFont);
    try
    {
      if (NMEAContext.getInstance().getCache().get(NMEADataCache.SAT_IN_VIEW) != null)
      {
        Map<Integer, SVData> hm = ( Map<Integer, SVData>)NMEAContext.getInstance().getCache().get(NMEADataCache.SAT_IN_VIEW);
        
        gr.setColor(Color.red);
        Font f = gr.getFont();
        gr.setFont(f.deriveFont(Font.BOLD));
        gr.drawString(hm.size() + " Satellites in view", 5, 20);
        int inUse = 0;
        // Display All Data Values:
        List<Object[]> dataTable = new ArrayList<Object[]>();
        dataTable.add(new Object[] {"Sat.#", "El.(\272)", "Z(\272)", "SNR(db)", Color.red}); // Titles
        for (Integer sn : hm.keySet())
        {
          SVData svd = hm.get(sn);
          int sID = svd.getSvID();
          int elev = svd.getElevation();
          int z = svd.getAzimuth();
          int snr = svd.getSnr();
          if (snr > 0)
          inUse++;
          int dz = (90 - elev);
          int x = center.x + (int)((dz / 90d) * radius * Math.sin(Math.toRadians(z)));
          int y = center.y - (int)((dz / 90d) * radius * Math.cos(Math.toRadians(z)));
          // Get the color from SNR
          gr.setColor(getSNRColor(snr));
          gr.fillOval(x - 10, y - 10, 20, 20);
          gr.drawString(Integer.toString(sID), x + 12, y + 12);
          System.out.println("Sat.#" + svd.getSvID() + " Elev:" + svd.getElevation() + ", Z:" + svd.getAzimuth() + ", SNR:" + svd.getSnr() + "db. ");
          dataTable.add(new Object[] { DF2.format(svd.getSvID()), 
                                       Integer.toString(svd.getElevation()), 
                                       Integer.toString(svd.getAzimuth()), 
                                       Integer.toString(svd.getSnr()), 
                                       Color.red });
        }
        gr.setColor(Color.red);
        gr.drawString(inUse + " Satellites in use", 5, 34);
        //
        int y = drawDataTable(dataTable, gr, 5, 40);
        gr.setFont(f);
      }
    }
    catch (Exception ex)
    {
      // No cache yet
    }
  } 

  private int drawDataTable(List<Object[]> data, Graphics gr, int startX, int startY)
  {
    int x = startX;
    // Determine biggest title width
    int maxLen1 = 0, maxLen2 = 0, maxLen3 = 0, maxLen4 = 0;
    for (Object[] sa : data)
    {
      String one   = (String)sa[0];
      String two   = (String)sa[1];
      String three = (String)sa[2];
      String four  = (String)sa[3];
      int len1 = gr.getFontMetrics(gr.getFont()).stringWidth(one);
      int len2 = gr.getFontMetrics(gr.getFont()).stringWidth(two);
      int len3 = gr.getFontMetrics(gr.getFont()).stringWidth(three);
      int len4 = gr.getFontMetrics(gr.getFont()).stringWidth(four);
      maxLen1 = Math.max(len1, maxLen1);
      maxLen2 = Math.max(len2, maxLen2);
      maxLen3 = Math.max(len3, maxLen3);
      maxLen4 = Math.max(len4, maxLen4);
    }
    Font f = gr.getFont();
    int fontSize = f.getSize();
    int y = startY + fontSize * 2;
    for (Object[] sa : data)
    {
      String s1 = (String)sa[0]; // Sat #
      String s2 = (String)sa[1]; // Elev
      String s3 = (String)sa[2]; // Z
      String s4 = (String)sa[3]; // SNR
      
      gr.setColor((Color)sa[4]);
      // Justified left
      gr.drawString(s1, x, y);                        
      // Justified right
      int l = gr.getFontMetrics(gr.getFont()).stringWidth(s2);
      gr.drawString(s2, maxLen1 + 5 + x + maxLen2 - l, y);
      // Justified right
      l = gr.getFontMetrics(gr.getFont()).stringWidth(s3);
      gr.drawString(s3, maxLen1 + maxLen2 + maxLen3 + 10 + x - l, y);
      // Justified right
      l = gr.getFontMetrics(gr.getFont()).stringWidth(s4);
      gr.drawString(s4, maxLen1 + maxLen2 + maxLen3 + maxLen4 + 15 + x - l, y);
      y += (fontSize + 2);
    }
    return y;
  }
  
  private static void drawGlossyCircularDisplay(Graphics2D g2d, Point center, int radius, Color lightColor, Color darkColor, float transparency)
  {
    g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, transparency));
    g2d.setPaint(null);

    g2d.setColor(darkColor);
    g2d.fillOval(center.x - radius, center.y - radius, 2 * radius, 2 * radius);

    Point gradientOrigin = new Point(center.x - radius,
                                     center.y - radius);
    GradientPaint gradient = new GradientPaint(gradientOrigin.x, 
                                               gradientOrigin.y, 
                                               lightColor, 
                                               gradientOrigin.x, 
                                               gradientOrigin.y + (2 * radius / 3), 
                                               darkColor); // vertical, light on top
    g2d.setPaint(gradient);
    g2d.fillOval((int)(center.x - (radius * 0.90)), 
                 (int)(center.y - (radius * 0.95)), 
                 (int)(2 * radius * 0.9), 
                 (int)(2 * radius * 0.95));
  }
  
  private static Color getSNRColor(int snr)
  {
    Color c = Color.lightGray;
    if (snr > 0)
      c = Color.red;
    if (snr > 10)
      c = Color.orange;
    if (snr > 20)
      c = Color.yellow;
    if (snr > 30)
      c = ChartColor.LIGHT_GREEN;
    if (snr > 40)
      c = Color.green;
    return c;
  }
}
